/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#003259',
        'secondary': '#aacaea',
        'surface-bright': '#31394d',
        'aqi-poor': '#F87171',
        'on-error': '#690005',
        'weather-sunny': '#4A90D9',
        'tertiary-container': '#8292a5',
        'on-primary-fixed': '#001c37',
        'surface-container-high': '#222a3d',
        'weather-night': '#0F172A',
        'surface': '#0b1326',
        'surface-container-highest': '#2d3449',
        'on-primary-container': '#002b4e',
        'weather-rainy': '#1A3A5C',
        'surface-container': '#171f33',
        'inverse-primary': '#0061a5',
        'on-tertiary-container': '#1b2b3a',
        'on-tertiary': '#223241',
        'error': '#ffb4ab',
        'inverse-surface': '#dae2fd',
        'weather-stormy': '#2C2C3E',
        'secondary-container': '#2c4c67',
        'aqi-moderate': '#FB923C',
        'primary': '#a0caff',
        'on-error-container': '#ffdad6',
        'weather-cloudy': '#6B7B8D',
        'aqi-hazardous': '#A78BFA',
        'glass-fill': 'rgba(255, 255, 255, 0.06)',
        'surface-container-low': '#131b2e',
        'primary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#b8c8dc',
        'error-container': '#93000a',
        'aqi-good': '#34D399',
        'surface-tint': '#a0caff',
        'on-secondary-fixed-variant': '#294a64',
        'weather-snowy': '#A8C8E8',
        'on-surface': '#dae2fd',
        'on-tertiary-fixed-variant': '#394859',
        'on-secondary': '#0f334d',
        'on-tertiary-fixed': '#0c1d2c',
        'surface-container-lowest': '#060e20',
        'on-secondary-fixed': '#001d32',
        'secondary-fixed': '#cde5ff',
        'on-surface-variant': '#c1c7d2',
        'secondary-fixed-dim': '#aacaea',
        'outline': '#8b919c',
        'on-primary-fixed-variant': '#00497e',
        'on-secondary-container': '#9cbcdb',
        'glass-stroke': 'rgba(255, 255, 255, 0.12)',
        'aqi-fair': '#FBBF24',
        'outline-variant': '#414751',
        'on-background': '#dae2fd',
        'primary-container': '#4f94dd',
        'background': '#0b1326',
        'inverse-on-surface': '#283044',
        'tertiary': '#b8c8dc',
        'surface-dim': '#0b1326',
        'tertiary-fixed': '#d4e4f9',
        'surface-variant': '#2d3449',
        'primary-fixed-dim': '#a0caff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '2.5rem',
        'card-gap': '1.5rem',
        'element-gap': '0.75rem',
        'section-margin': '3rem',
      },
      fontFamily: {
        'display-temp': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'display-temp': ['120px', { lineHeight: '120px', letterSpacing: '-0.04em', fontWeight: '200' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      animation: {
        'float': 'subtle-float 6s ease-in-out infinite',
        'spin-slow': 'spin-slow 12s linear infinite',
      },
      keyframes: {
        'subtle-float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'spin-slow': {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
}